baseURL = 'https://previ.github.io/spaziolaportaverde.it/'
languageCode = 'it-it'
title = 'Spazio La Porta Verde'

[params]
    description = "Centro Culturale e Galleria d'Arte a Milano"
    author = "Gabriella Ventavoli"

[imaging]
    resampleFilter = "CatmullRom"
    quality        = 85
    anchor         = "smart"
