baseURL = '/'
languageCode = 'it-it'
title = 'Spazio La Porta Verde'
canonifyURLs = true

[params]
    description = "Centro Culturale e Galleria d'Arte a Milano"
    author = "Gabriella Ventavoli"
    googleAnalytics = "G-H5NTQ3C2XQ"

[imaging]
    resampleFilter = "CatmullRom"
    quality        = 85
    anchor         = "smart"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = ""
        weight = 10
    [[menu.main]]
        identifier = "chisiamo"
        name = "Chi Siamo"
        url = "chi-siamo/"
        weight = 20
    [[menu.main]]
        identifier = "finalita"
        name = "Finalità"
        url = "finalita/"
        weight = 30
    [[menu.main]]
        identifier = "spazio"
        name = "Lo Spazio"
        url = "lo-spazio/"
        weight = 40
    [[menu.main]]
        identifier = "mostre"
        name = "Mostre ed Eventi"
        url = "mostre/"
        weight = 50
    [[menu.main]]
        identifier = "gallerie"
        name = "Gallerie"
        url = "gallerie/"
        weight = 52
    [[menu.main]]
        identifier = "contatti"
        name = "Contatti"
        url = "contatti/"
        weight = 70
